export const demoData = {
  admins: [{ id: 'admin_001', email: 'admin@ayoginanjar.test', passcode: 'password123', name: 'Ayo Ginanjar Admin' }],
  productCategories: [{ id: 'pcat_001', name: 'Marketing Digital', slug: 'marketing-digital', description: 'Panduan dan template promosi online.', icon: 'MKT', isActive: true, sortOrder: 1 }],
  products: [{ id: 'prod_001', title: 'Template Konten 30 Hari untuk UMKM', slug: 'template-konten-30-hari-umkm', shortDescription: 'Kalender konten siap pakai untuk promosi online.', fullDescription: 'Template ini membantu pemilik usaha menyusun konten harian secara rapi dan konsisten.', benefits: ['Menghemat waktu membuat ide konten'], targetAudience: 'Pemilik UMKM dan kreator pemula.', deliverables: ['Template kalender konten'], categoryId: 'pcat_001', thumbnail: 'https://placehold.co/900x600/f97316/ffffff?text=Template+Konten', priceLabel: 'Mulai Rp49.000', originalPrice: 99000, discountPrice: 49000, partnerUrl: 'https://example.com/product/template-konten', checkoutButtonText: 'Lihat Produk Partner', isFeatured: true, isActive: true, seoTitle: 'Template Konten 30 Hari untuk UMKM', seoDescription: 'Template konten digital untuk membantu UMKM promosi online.', clickCount: 0 }],
  blogCategories: [{ id: 'bcat_001', name: 'Strategi Digital', slug: 'strategi-digital', description: 'Artikel pemasaran dan bisnis online.', isActive: true }],
  blogPosts: [{ id: 'post_001', title: 'Cara Memilih Produk Digital', slug: 'cara-memilih-produk-digital', excerpt: 'Cara menilai produk digital sebelum direkomendasikan.', content: 'Produk digital yang baik harus relevan dengan audiens, punya manfaat jelas, dan mudah dipahami.', coverImage: 'https://placehold.co/1000x600/f97316/ffffff?text=Digital+Guide', categoryId: 'bcat_001', status: 'published', relatedProductIds: ['prod_001'] }],
  homepage: { heroTitle: 'Temukan Produk Digital yang Membantu Bisnismu Bergerak Lebih Cepat', heroSubtitle: 'Ayo Ginanjar mengkurasi produk digital yang praktis untuk marketing, branding, sales, dan bisnis.', ctaText: 'Lihat Katalog Produk', ctaLink: '/produk', secondaryCtaText: 'Tentang Saya', secondaryCtaLink: '/tentang-saya', aboutShort: 'Pusat rekomendasi produk digital yang mudah dipahami dan bisa langsung dipakai.' },
  settings: { siteName: 'Ayo Ginanjar', siteDescription: 'Personal brand dan katalog produk digital.', brandName: 'Ayo Ginanjar', alternateName: 'ErgioG', contactEmail: 'halo@ayoginanjar.test', contactWhatsapp: '+62 800-0000-0000', instagramUrl: 'https://example.com/instagram', defaultMetaImage: 'https://placehold.co/1200x630/f97316/ffffff?text=Ayo+Ginanjar', metaPixelId: '' },
  productClicks: [],
  events: []
};
